In [16]:
%matplotlib widget

In [17]:
import numpy as np
import emg3d 
import empymod as ep
import pandas as pd
from scipy.constants import mu_0
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import time
import sys
sys.path.insert(1, 'src')

#from Plot import grid

## Upload data and sort

In [18]:
OUT = np.load('data/data3D_slope5.pkl', allow_pickle=True)

In [5]:
OUT

    geom  src_x  rec_x  midpx  offset        op        ip
0     H2   -4.0   -2.0  -3.00     2.0  0.005352  0.003999
1     H4   -4.0    0.0  -2.00     4.0  0.029752  0.028811
2     H8   -4.0    4.0   0.00     8.0  0.081399  0.148963
3     V2   -4.0   -2.0  -3.00     2.0  0.003397  0.002037
4     V4   -4.0    0.0  -2.00     4.0  0.020161  0.015571
..   ...    ...    ...    ...     ...       ...       ...
400   V4   40.0   44.0  42.00     4.0  0.032423  0.022773
401   V8   40.0   48.0  44.00     8.0  0.137991  0.139889
402   P2   40.0   42.1  41.05     2.1  0.004650  0.001402
403   P4   40.0   44.1  42.05     4.1  0.039629  0.017958
404   P8   40.0   48.1  44.05     8.1  0.225617  0.175516

[405 rows x 7 columns]

In [6]:
OUT_sorted = OUT.sort_values(by='geom')

In [7]:
OUT_sorted

    geom  src_x  rec_x  midpx  offset        op        ip
0     H2   -4.0   -2.0   -3.0     2.0  0.005352  0.003999
333   H2   33.0   35.0   34.0     2.0  0.008796  0.005872
99    H2    7.0    9.0    8.0     2.0  0.005476  0.004185
216   H2   20.0   22.0   21.0     2.0  0.006924  0.004983
90    H2    6.0    8.0    7.0     2.0  0.005434  0.004156
..   ...    ...    ...    ...     ...       ...       ...
176   V8   15.0   23.0   19.0     8.0  0.111889  0.117170
284   V8   27.0   35.0   31.0     8.0  0.131817  0.133599
374   V8   37.0   45.0   41.0     8.0  0.138115  0.139946
356   V8   35.0   43.0   39.0     8.0  0.137597  0.139401
239   V8   22.0   30.0   26.0     8.0  0.124773  0.127558

[405 rows x 7 columns]

In [8]:
npos = int(len(OUT_sorted)/9)

In [9]:
npos

45

In [10]:
data_3D = np.zeros((npos-3,18))

pos=0
for p in range(-3,npos):
    #print(OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <p +1.06)])

    dat = np.hstack((OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['op'],
                     OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['ip'])) 
    if dat.size == 0:
        continue
    if dat.size == 18:
        data_3D[pos,:] = dat
        #print('pos:', pos)
        pos += 1

In [11]:
np.save('data/data3D_slope5_sorted.pkl', data_3D[1:41])

In [12]:
np.shape(data_3D[1:41])

(40, 18)