In [1]:
%matplotlib widget

In [2]:
import numpy as np
import emg3d 
import empymod as ep
import pandas as pd
from scipy.constants import mu_0
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import time
import sys
sys.path.insert(1, 'src')

#from Plot import grid

## Upload data and sort

In [3]:
OUT = np.load('data/data3D_slope5_f.pkl', allow_pickle=True)

In [4]:
OUT

    geom  src_x  rec_x  midpx  offset        op        ip
0     H2   -4.0   -2.0  -3.00     2.0  0.049737  0.020285
1     H4   -4.0    0.0  -2.00     4.0  0.094363  0.102679
2     H8   -4.0    4.0   0.00     8.0  0.086370  0.275953
3     V2   -4.0   -2.0  -3.00     2.0  0.059638  0.011838
4     V4   -4.0    0.0  -2.00     4.0  0.192810  0.072162
..   ...    ...    ...    ...     ...       ...       ...
400   V4   40.0   44.0  42.00     4.0  0.187391  0.059875
401   V8   40.0   48.0  44.00     8.0  0.431287  0.266466
402   P2   40.0   42.1  41.05     2.1  0.078333  0.008957
403   P4   40.0   44.1  42.05     4.1  0.253781  0.068749
404   P8   40.0   48.1  44.05     8.1  0.564848  0.365192

[405 rows x 7 columns]

In [5]:
OUT_sorted = OUT.sort_values(by='geom')

In [6]:
OUT_sorted

    geom  src_x  rec_x  midpx  offset        op        ip
0     H2   -4.0   -2.0   -3.0     2.0  0.049737  0.020285
333   H2   33.0   35.0   34.0     2.0  0.047893  0.017049
99    H2    7.0    9.0    8.0     2.0  0.049757  0.020148
216   H2   20.0   22.0   21.0     2.0  0.049088  0.018659
90    H2    6.0    8.0    7.0     2.0  0.049759  0.020200
..   ...    ...    ...    ...     ...       ...       ...
176   V8   15.0   23.0   19.0     8.0  0.437771  0.298579
284   V8   27.0   35.0   31.0     8.0  0.432160  0.273943
374   V8   37.0   45.0   41.0     8.0  0.430981  0.267718
356   V8   35.0   43.0   39.0     8.0  0.430575  0.267758
239   V8   22.0   30.0   26.0     8.0  0.432957  0.281845

[405 rows x 7 columns]

In [7]:
npos = int(len(OUT_sorted)/9)

In [8]:
npos

45

In [10]:
data_3D = np.zeros((npos-3,18))

pos=0
for p in range(-3,npos):
    #print(OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <p +1.06)])

    dat = np.hstack((OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['op'],
                     OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['ip'])) 
    if dat.size == 0:
        continue
    if dat.size == 18:
        data_3D[pos,:] = dat
        #print('pos:', pos)
        pos += 1

In [11]:
np.save('data/data3D_slope5_f_sorted.pkl', data_3D[1:41])

In [12]:
np.shape(data_3D[1:41])

(40, 18)